spring:
    application:
        name: CHAT_APP
    datasource:
        driver-class-name:  com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/chat_app
        username: root
        password: 123456
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                type:
                    json_format_mapper: com.huyhoang25.chatapp.configuration.CustomHibernateJsonFormatter
    data:
        redis:
            host: localhost
            port: 6379
jwt:
    secret-key: 91eedeb7e798938acd57a0326e341e9709987f4d303f45c83ea7bccabf3c0bbb
logging:
    level:
        org:
            springframework:
                security: DEBUG
            web:
                socket: DEBUG
