name: "chat-app"

services:
  mysql:
    container_name: mysql
    image: mysql:8.3.0
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chat_app
  redis-server:
    image: redis:8.0
    container_name: redis-server-chatapp
    hostname: redis-server
    ports:
      - "6379:6379"
      
volumes:
  mysql-data:
