events {}

http {
    # Định nghĩa nhóm server với tên khác một chút để tránh nhầm lẫn
    upstream backend_server {
        server backend:8080;
    }

    upstream frontend_server {
        server frontend:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://frontend_server;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/ {
            proxy_pass http://backend_server/; # Sử dụng tên upstream đã đổi
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /ws {
            proxy_pass http://backend_server/ws; # Sử dụng upstream thay vì gọi trực tiếp port
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }
    }
}